import Head from 'next/head';

import Form from '../components/Form';
import { useSession } from 'next-auth/react';

export default function Home() {
  const { data: session, status } = useSession();

  if (status === 'loading') {
    return <p>...</p>;
  }
  return (
    <div>
      <Head>
        <title>Form and Authentication</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        {session ? (
          <p>You are looged in!</p>
        ) : (
          <p>
            You are not logged in 🙁. <a href='/api/auth/signin'>login</a>{' '}
          </p>
        )}
      </div>
    </div>
  );
}
